language: android
android:
  components:
    - build-tools-23.0.2
    - android-22

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # No emulator - for now